name: build
on: push
jobs:
  build:
    uses: ashep/go-ci/.github/workflows/go-app.yaml@v1
    with:
      app_name: ${{ github.event.repository.name }}
      app_version: ${{ github.ref_name }}
      registry_user: ${{ vars.REGISTRY_USER }}
    secrets:
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
